// vue2.7/src/pages/ProfilePage.vue
<script setup>
  import { computed } from 'vue';
  import { useProfile } from 'src/composables/use-profile';
  import { timeToYYYYMMDD } from 'src/utils/time';
  import BigAvatar from 'src/components/profile/BigAvatar.vue';
  import ItemCount from 'src/components/profile/ItemCount.vue';
  import VSection from 'src/components/atoms/VSection.vue';
  import VLabel from 'src/components/atoms/VLabel.vue';

  const username = 'dev2820';
  const { profile } = useProfile(username);

  const avatarAttrs = computed(() => ({
    src: profile.value.avatarUrl,
    alt: `${profile.value.name}'s avatar`,
    width: 140,
    height: 140
  }));

  const createdAt = computed(() => timeToYYYYMMDD(new Date(profile.value.createdAt)));
</script>

<template>
  <main v-if="profile">
    <big-avatar id="avatar" v-bind="avatarAttrs"></big-avatar>
    <h2>{{ profile.name }}</h2>
    <v-section label="bio" id="bio">
      <p>{{ profile.bio }}</p>
    </v-section>
    <v-section label="summary" id="summary">
      <item-count class="count" :count="profile.totalPublicRepos" :label="'Repos'"></item-count>
      <item-count class="count" :count="profile.totalFollowers" :label="'Followers'"></item-count>
      <item-count class="count" :count="profile.totalFollowing" :label="'Following'"></item-count>
    </v-section>
    <div class="card meta-container">
      <v-section label="meta" id="meta">
        <v-label :icon="'calendar'" :text="createdAt"></v-label>
        <v-label :icon="'map-pin'" :text="profile.location"></v-label>
        <a :href="profile.githubUrl" target="_blank">
          <v-label :icon="'github-mark-white'" :text="'github'"></v-label>
        </a>
      </v-section>
    </div>
  </main>
</template>

<style scoped>
  main {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  #avatar {
    border-radius: 9999px;
    margin: 1rem 0;
  }

  h2 {
    margin: 1rem 0;
  }

  li {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  #meta {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  #bio {
    margin: 1rem 0;
  }

  #summary {
    align-self: left;
    display: flex;
    flex-direction: row;
    gap: 1rem;
    justify-content: center;
    margin: 2rem 0;
  }

  .count {
    font-size: 2rem;
    width: 5rem;
  }
  .meta-container {
    width: 100%;
  }
  .card {
    border-radius: 0.75rem;
    padding: 2rem;
    box-shadow:
      inset 0 0 0.5px 1px hsla(0, 0%, 100%, 0.1),
      0 0 0 1px hsla(230, 13%, 9%, 0.075),
      0 0.3px 0.4px hsla(230, 13%, 9%, 0.02),
      0 0.9px 1.5px hsla(230, 13%, 9%, 0.045),
      0 3.5px 6px hsla(230, 13%, 9%, 0.09);
  }
</style>

// react18/src/pages/ProfilePage/ProfilePage.tsx
import { useParams } from 'react-router-dom';

import { IconText, Section } from 'src/components/atoms';
import { RoundAvatar } from 'src/components/profile/RoundAvatar';
import { useProfile, type Profile } from 'src/hooks/use-profile';
import { ItemCount } from 'src/components/profile/ItemCount';
import { capitalize } from 'src/utils/string';
import { formatYYYYMMDD } from 'src/utils/date';

import style from './ProfilePage.module.css';

export function ProfilePage() {
  const { id } = useParams();
  const { profile } = useProfile(id ?? '');

  return <div className={style['_']}>{profile && <Profile profile={profile} />}</div>;
}

const Profile = ({ profile }: { profile: Profile }) => {
  const {
    name,
    avatarUrl,
    bio,
    totalFollowers,
    totalFollowing,
    totalPublicRepos,
    createdAt,
    location,
    githubUrl
  } = profile;
  const alt = `${profile.name}'s avatar`;
  return (
    <>
      <RoundAvatar className={style['avatar']} src={avatarUrl} size={140} alt={alt}></RoundAvatar>
      <h2 className={style['name']}>{name}</h2>
      <Section className={style['bio']} label="bio">
        <p>{bio}</p>
      </Section>
      <Section label="summary" className={style['summary']}>
        <ItemCount
          className={style['item-count']}
          count={totalPublicRepos}
          label="Repos"
        ></ItemCount>
        <ItemCount
          className={style['item-count']}
          count={totalFollowers}
          label="Followers"
        ></ItemCount>
        <ItemCount
          className={style['item-count']}
          count={totalFollowing}
          label="Following"
        ></ItemCount>
      </Section>
      <Section label="meta" className={`card ${style['meta']}`}>
        <IconText name="calendar">
          {formatYYYYMMDD(new Date(createdAt), { separator: '-' })}
        </IconText>
        <IconText name="map-pin">{capitalize(location)}</IconText>
        <a href={githubUrl} target="_blank">
          <IconText name="github-mark-white">Link to Github</IconText>
        </a>
      </Section>
    </>
  );
};
