// react/src/components/atom/RoundAvatar.tsx
import { HTMLAttributes } from "react";

import "./RoundAvatar.css";

export interface Props extends HTMLAttributes<HTMLImageElement> {
  size?: number;
  alt?: string;
  src: string;
}
export function RoundAvatar({size, src,className="",alt="", ...props}:Props) {
  return (
    <img className={"round-avatar " + className} src={src} {...props} width={size} height={size} alt={alt}></img>
  )
}

// vue/src/components/atom/RoundAvatar.vue
<script setup lang='ts'>
interface Props {
  imgUrl: string;
  size: number;
  alt?: string;
}
withDefaults(defineProps<Props>(),{
  imgUrl: '',
  size: 0,
  alt: ''
})

</script>

<template>
  <img
    :src="imgUrl"
    :height="size"
    :width="size"
    :alt="alt"
  >
</template>


<style scoped>
img {
  border-radius:9999px;
}
</style>
