// vue/src/components/atom/RoundAvatar.vue
<script setup lang='ts'>
interface Props {
  imgUrl: string;
  size: number;
  alt?: string;
}
withDefaults(defineProps<Props>(),{
  imgUrl: '',
  size: 0,
  alt: ''
})

</script>

<template>
  <img
    :src="imgUrl"
    :height="size"
    :width="size"
    :alt="alt"
  >
</template>


<style scoped>
img {
  border-radius:9999px;
}
</style>

// react18/src/components/profile/RoundAvatar/RoundAvatar.tsx
import { ImgHTMLAttributes } from 'react';

import style from './RoundAvatar.module.css';

interface Props extends ImgHTMLAttributes<HTMLImageElement> {
  size?: number;
}

export const RoundAvatar = ({ size = 100, className, ...props }: Props) => {
  return (
    <img
      className={`${style['round-avatar']} ${className}`}
      width={size}
      height={size}
      {...props}
    />
  );
};
